{
 "title": "Chapter 14 Cloud Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "period",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "CloudWatch Monitoring",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expression": "REMOVE_EMPTY(SEARCH('{AWS/Lambda} MetricName=\"Invocations\"', 'Sum', $period))/$period",
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "period": "$period",
     "queryMode": "Metrics",
     "region": "default"
    }
   ]
  },
  {
   "title": "Azure Monitor",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "appInsights": {
      "dimension": "none",
      "metricName": "select",
      "rawQuery": false,
      "rawQueryString": "",
      "timeColumn": "timestamp",
      "timeGrain": "auto",
      "valueColumn": ""
     },
     "azureLogAnalytics": {
      "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
      "resultFormat": "time_series",
      "workspace": "07b8c4ac-3fb7-4105-a2ce-9f096e66c0e6"
     },
     "azureMonitor": {
      "aggOptions": [
       "Average",
       "Maximum",
       "Minimum"
      ],
      "aggregation": "Average",
      "allowedTimeGrainsMs": [
       60000,
       300000,
       900000,
       1800000,
       3600000,
       21600000,
       43200000,
       86400000
      ],
      "dimension": "None",
      "dimensionFilter": "*",
      "dimensions": [
       { "$$hashKey": "object:380", "text": "None", "value": "None" },
       { "$$hashKey": "object:381", "text": "Request performance", "value": "request/performanceBucket" },
       { "$$hashKey": "object:382", "text": "Result code", "value": "request/resultCode" },
       { "$$hashKey": "object:383", "text": "Is traffic synthetic", "value": "operation/synthetic" },
       { "$$hashKey": "object:384", "text": "Cloud role instance", "value": "cloud/roleInstance" },
       { "$$hashKey": "object:385", "text": "Successful request", "value": "request/success" },
       { "$$hashKey": "object:386", "text": "Cloud role name", "value": "cloud/roleName" }
      ],
      "metricDefinition": "microsoft.insights/components",
      "metricName": "requests/duration",
      "metricNamespace": "microsoft.insights/components",
      "resourceGroup": "LogResource",
      "resourceName": "LearnGrafana7",
      "timeGrain": "auto",
      "timeGrains": [
       { "$$hashKey": "object:371", "text": "auto", "value": "auto" },
       { "$$hashKey": "object:372", "text": "1 minute", "value": "PT1M" },
       { "$$hashKey": "object:373", "text": "5 minutes", "value": "PT5M" },
       { "$$hashKey": "object:374", "text": "15 minutes", "value": "PT15M" },
       { "$$hashKey": "object:375", "text": "30 minutes", "value": "PT30M" },
       { "$$hashKey": "object:376", "text": "1 hour", "value": "PT1H" },
       { "$$hashKey": "object:377", "text": "6 hours", "value": "PT6H" },
       { "$$hashKey": "object:378", "text": "12 hours", "value": "PT12H" },
       { "$$hashKey": "object:379", "text": "1 day", "value": "P1D" }
      ],
      "top": "10"
     },
     "subscription": "aa2e229a-71e5-4f9b-9fad-7b20bd857215"
    }
   ]
  },
  {
   "title": "Stackdriver Monitoring",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "",
      "alignmentPeriod": "stackdriver-auto",
      "crossSeriesReducer": "REDUCE_MEAN",
      "filters": [],
      "groupBys": [],
      "metricKind": "DELTA",
      "metricType": "logging.googleapis.com/byte_count",
      "perSeriesAligner": "ALIGN_DELTA",
      "projectName": "polar-elevator-275803",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  }
 ]
}