{
 "title": "Chapter 7.02 Low Density",
 "time": { "from": "now/d", "to": "now" },
 "panels": [
  {
   "title": "Station",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "content": "\n<h1><center>San Francisco CA (KSFO)</center></h1>\n\n\n",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "High Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Low Temperature",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "panelId": 4 }
   ]
  },
  {
   "title": "Dew Point",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "dewpoint",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Barometer Reading",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "pressurekpa" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "barometricPressure",
     "query": "SELECT mean(\"value\")  / 1000 FROM \"barometricPressure\" WHERE $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Barometer Reading",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "barometricPressure",
     "query": "SELECT /abs(derivative(mean(\"value\"), 1h))) FROM \"barometricPressure\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "1h" ], "type": "derivative" },
       {
        "params": [
         "/abs(derivative(mean(\"value\"), 1h))"
        ],
        "type": "math"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Visibility",
   "type": "bargauge",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "lengthkm" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "visibility",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "windSpeed",
     "query": "SELECT distinct(\"value\")  / 1000*3600 FROM \"windSpeed\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000*3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Wind Speed",
   "type": "stat",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "velocitykmh" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "windGust",
     "query": "SELECT distinct(\"value\")  / 1000* 3600 FROM \"windGust\" WHERE (\"station\" = 'KSFO') AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000* 3600" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Wind Direction",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "$col $measurement",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "windDirection",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  },
  {
   "title": "Current Conditions",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "textDescription",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "station", "operator": "=", "value": "KSFO" }
     ]
    }
   ]
  }
 ]
}